// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mediguide/aiworker/v1/aiworker.proto

package aiworkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AskRAGRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Question       string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Language       string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Country        string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	ProgramArea    string                 `protobuf:"bytes,4,opt,name=program_area,json=programArea,proto3" json:"program_area,omitempty"`
	HistorySummary string                 `protobuf:"bytes,5,opt,name=history_summary,json=historySummary,proto3" json:"history_summary,omitempty"`
	RecentMessages []*ChatMessage         `protobuf:"bytes,6,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	TopK           int32                  `protobuf:"varint,7,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AskRAGRequest) Reset() {
	*x = AskRAGRequest{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRAGRequest) ProtoMessage() {}

func (x *AskRAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRAGRequest.ProtoReflect.Descriptor instead.
func (*AskRAGRequest) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{1}
}

func (x *AskRAGRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskRAGRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AskRAGRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AskRAGRequest) GetProgramArea() string {
	if x != nil {
		return x.ProgramArea
	}
	return ""
}

func (x *AskRAGRequest) GetHistorySummary() string {
	if x != nil {
		return x.HistorySummary
	}
	return ""
}

func (x *AskRAGRequest) GetRecentMessages() []*ChatMessage {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

func (x *AskRAGRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	SourceName    string                 `protobuf:"bytes,4,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceVersion string                 `protobuf:"bytes,5,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	PageStart     int32                  `protobuf:"varint,6,opt,name=page_start,json=pageStart,proto3" json:"page_start,omitempty"`
	PageEnd       int32                  `protobuf:"varint,7,opt,name=page_end,json=pageEnd,proto3" json:"page_end,omitempty"`
	Similarity    float32                `protobuf:"fixed32,8,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{2}
}

func (x *Citation) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Citation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Citation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Citation) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Citation) GetSourceVersion() string {
	if x != nil {
		return x.SourceVersion
	}
	return ""
}

func (x *Citation) GetPageStart() int32 {
	if x != nil {
		return x.PageStart
	}
	return 0
}

func (x *Citation) GetPageEnd() int32 {
	if x != nil {
		return x.PageEnd
	}
	return 0
}

func (x *Citation) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

type RetrievedChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PageStart     int32                  `protobuf:"varint,4,opt,name=page_start,json=pageStart,proto3" json:"page_start,omitempty"`
	PageEnd       int32                  `protobuf:"varint,5,opt,name=page_end,json=pageEnd,proto3" json:"page_end,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	ProgramArea   string                 `protobuf:"bytes,7,opt,name=program_area,json=programArea,proto3" json:"program_area,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	SourceName    string                 `protobuf:"bytes,9,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceVersion string                 `protobuf:"bytes,10,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	Similarity    float32                `protobuf:"fixed32,11,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedChunk) Reset() {
	*x = RetrievedChunk{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedChunk) ProtoMessage() {}

func (x *RetrievedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedChunk.ProtoReflect.Descriptor instead.
func (*RetrievedChunk) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{3}
}

func (x *RetrievedChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RetrievedChunk) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RetrievedChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrievedChunk) GetPageStart() int32 {
	if x != nil {
		return x.PageStart
	}
	return 0
}

func (x *RetrievedChunk) GetPageEnd() int32 {
	if x != nil {
		return x.PageEnd
	}
	return 0
}

func (x *RetrievedChunk) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RetrievedChunk) GetProgramArea() string {
	if x != nil {
		return x.ProgramArea
	}
	return ""
}

func (x *RetrievedChunk) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RetrievedChunk) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *RetrievedChunk) GetSourceVersion() string {
	if x != nil {
		return x.SourceVersion
	}
	return ""
}

func (x *RetrievedChunk) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

type Safety struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Grounded           bool                   `protobuf:"varint,1,opt,name=grounded,proto3" json:"grounded,omitempty"`
	Provider           string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	StandaloneQuestion string                 `protobuf:"bytes,4,opt,name=standalone_question,json=standaloneQuestion,proto3" json:"standalone_question,omitempty"`
	GenerationError    string                 `protobuf:"bytes,5,opt,name=generation_error,json=generationError,proto3" json:"generation_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Safety) Reset() {
	*x = Safety{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Safety) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Safety) ProtoMessage() {}

func (x *Safety) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Safety.ProtoReflect.Descriptor instead.
func (*Safety) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{4}
}

func (x *Safety) GetGrounded() bool {
	if x != nil {
		return x.Grounded
	}
	return false
}

func (x *Safety) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Safety) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Safety) GetStandaloneQuestion() string {
	if x != nil {
		return x.StandaloneQuestion
	}
	return ""
}

func (x *Safety) GetGenerationError() string {
	if x != nil {
		return x.GenerationError
	}
	return ""
}

type AskRAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Citations     []*Citation            `protobuf:"bytes,2,rep,name=citations,proto3" json:"citations,omitempty"`
	Retrieved     []*RetrievedChunk      `protobuf:"bytes,3,rep,name=retrieved,proto3" json:"retrieved,omitempty"`
	Safety        *Safety                `protobuf:"bytes,4,opt,name=safety,proto3" json:"safety,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRAGResponse) Reset() {
	*x = AskRAGResponse{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRAGResponse) ProtoMessage() {}

func (x *AskRAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRAGResponse.ProtoReflect.Descriptor instead.
func (*AskRAGResponse) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{5}
}

func (x *AskRAGResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskRAGResponse) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *AskRAGResponse) GetRetrieved() []*RetrievedChunk {
	if x != nil {
		return x.Retrieved
	}
	return nil
}

func (x *AskRAGResponse) GetSafety() *Safety {
	if x != nil {
		return x.Safety
	}
	return nil
}

type RunIngestionJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunIngestionJobRequest) Reset() {
	*x = RunIngestionJobRequest{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunIngestionJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunIngestionJobRequest) ProtoMessage() {}

func (x *RunIngestionJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunIngestionJobRequest.ProtoReflect.Descriptor instead.
func (*RunIngestionJobRequest) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{6}
}

func (x *RunIngestionJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RunIngestionJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunIngestionJobResponse) Reset() {
	*x = RunIngestionJobResponse{}
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunIngestionJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunIngestionJobResponse) ProtoMessage() {}

func (x *RunIngestionJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediguide_aiworker_v1_aiworker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunIngestionJobResponse.ProtoReflect.Descriptor instead.
func (*RunIngestionJobResponse) Descriptor() ([]byte, []int) {
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP(), []int{7}
}

func (x *RunIngestionJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunIngestionJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunIngestionJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mediguide_aiworker_v1_aiworker_proto protoreflect.FileDescriptor

const file_mediguide_aiworker_v1_aiworker_proto_rawDesc = "" +
	"\n" +
	"$mediguide/aiworker/v1/aiworker.proto\x12\x15mediguide.aiworker.v1\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8f\x02\n" +
	"\rAskRAGRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12!\n" +
	"\fprogram_area\x18\x04 \x01(\tR\vprogramArea\x12'\n" +
	"\x0fhistory_summary\x18\x05 \x01(\tR\x0ehistorySummary\x12K\n" +
	"\x0frecent_messages\x18\x06 \x03(\v2\".mediguide.aiworker.v1.ChatMessageR\x0erecentMessages\x12\x13\n" +
	"\x05top_k\x18\a \x01(\x05R\x04topK\"\xf7\x01\n" +
	"\bCitation\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1f\n" +
	"\vsource_name\x18\x04 \x01(\tR\n" +
	"sourceName\x12%\n" +
	"\x0esource_version\x18\x05 \x01(\tR\rsourceVersion\x12\x1d\n" +
	"\n" +
	"page_start\x18\x06 \x01(\x05R\tpageStart\x12\x19\n" +
	"\bpage_end\x18\a \x01(\x05R\apageEnd\x12\x1e\n" +
	"\n" +
	"similarity\x18\b \x01(\x02R\n" +
	"similarity\"\xcb\x02\n" +
	"\x0eRetrievedChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"page_start\x18\x04 \x01(\x05R\tpageStart\x12\x19\n" +
	"\bpage_end\x18\x05 \x01(\x05R\apageEnd\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12!\n" +
	"\fprogram_area\x18\a \x01(\tR\vprogramArea\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x1f\n" +
	"\vsource_name\x18\t \x01(\tR\n" +
	"sourceName\x12%\n" +
	"\x0esource_version\x18\n" +
	" \x01(\tR\rsourceVersion\x12\x1e\n" +
	"\n" +
	"similarity\x18\v \x01(\x02R\n" +
	"similarity\"\xb4\x01\n" +
	"\x06Safety\x12\x1a\n" +
	"\bgrounded\x18\x01 \x01(\bR\bgrounded\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12/\n" +
	"\x13standalone_question\x18\x04 \x01(\tR\x12standaloneQuestion\x12)\n" +
	"\x10generation_error\x18\x05 \x01(\tR\x0fgenerationError\"\xe3\x01\n" +
	"\x0eAskRAGResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12=\n" +
	"\tcitations\x18\x02 \x03(\v2\x1f.mediguide.aiworker.v1.CitationR\tcitations\x12C\n" +
	"\tretrieved\x18\x03 \x03(\v2%.mediguide.aiworker.v1.RetrievedChunkR\tretrieved\x125\n" +
	"\x06safety\x18\x04 \x01(\v2\x1d.mediguide.aiworker.v1.SafetyR\x06safety\"/\n" +
	"\x16RunIngestionJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"b\n" +
	"\x17RunIngestionJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xda\x01\n" +
	"\x0fAIWorkerService\x12U\n" +
	"\x06AskRAG\x12$.mediguide.aiworker.v1.AskRAGRequest\x1a%.mediguide.aiworker.v1.AskRAGResponse\x12p\n" +
	"\x0fRunIngestionJob\x12-.mediguide.aiworker.v1.RunIngestionJobRequest\x1a..mediguide.aiworker.v1.RunIngestionJobResponseB*Z(mediguide/internal/aiworkerpb;aiworkerpbb\x06proto3"

var (
	file_mediguide_aiworker_v1_aiworker_proto_rawDescOnce sync.Once
	file_mediguide_aiworker_v1_aiworker_proto_rawDescData []byte
)

func file_mediguide_aiworker_v1_aiworker_proto_rawDescGZIP() []byte {
	file_mediguide_aiworker_v1_aiworker_proto_rawDescOnce.Do(func() {
		file_mediguide_aiworker_v1_aiworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mediguide_aiworker_v1_aiworker_proto_rawDesc), len(file_mediguide_aiworker_v1_aiworker_proto_rawDesc)))
	})
	return file_mediguide_aiworker_v1_aiworker_proto_rawDescData
}

var file_mediguide_aiworker_v1_aiworker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mediguide_aiworker_v1_aiworker_proto_goTypes = []any{
	(*ChatMessage)(nil),             // 0: mediguide.aiworker.v1.ChatMessage
	(*AskRAGRequest)(nil),           // 1: mediguide.aiworker.v1.AskRAGRequest
	(*Citation)(nil),                // 2: mediguide.aiworker.v1.Citation
	(*RetrievedChunk)(nil),          // 3: mediguide.aiworker.v1.RetrievedChunk
	(*Safety)(nil),                  // 4: mediguide.aiworker.v1.Safety
	(*AskRAGResponse)(nil),          // 5: mediguide.aiworker.v1.AskRAGResponse
	(*RunIngestionJobRequest)(nil),  // 6: mediguide.aiworker.v1.RunIngestionJobRequest
	(*RunIngestionJobResponse)(nil), // 7: mediguide.aiworker.v1.RunIngestionJobResponse
}
var file_mediguide_aiworker_v1_aiworker_proto_depIdxs = []int32{
	0, // 0: mediguide.aiworker.v1.AskRAGRequest.recent_messages:type_name -> mediguide.aiworker.v1.ChatMessage
	2, // 1: mediguide.aiworker.v1.AskRAGResponse.citations:type_name -> mediguide.aiworker.v1.Citation
	3, // 2: mediguide.aiworker.v1.AskRAGResponse.retrieved:type_name -> mediguide.aiworker.v1.RetrievedChunk
	4, // 3: mediguide.aiworker.v1.AskRAGResponse.safety:type_name -> mediguide.aiworker.v1.Safety
	1, // 4: mediguide.aiworker.v1.AIWorkerService.AskRAG:input_type -> mediguide.aiworker.v1.AskRAGRequest
	6, // 5: mediguide.aiworker.v1.AIWorkerService.RunIngestionJob:input_type -> mediguide.aiworker.v1.RunIngestionJobRequest
	5, // 6: mediguide.aiworker.v1.AIWorkerService.AskRAG:output_type -> mediguide.aiworker.v1.AskRAGResponse
	7, // 7: mediguide.aiworker.v1.AIWorkerService.RunIngestionJob:output_type -> mediguide.aiworker.v1.RunIngestionJobResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mediguide_aiworker_v1_aiworker_proto_init() }
func file_mediguide_aiworker_v1_aiworker_proto_init() {
	if File_mediguide_aiworker_v1_aiworker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mediguide_aiworker_v1_aiworker_proto_rawDesc), len(file_mediguide_aiworker_v1_aiworker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediguide_aiworker_v1_aiworker_proto_goTypes,
		DependencyIndexes: file_mediguide_aiworker_v1_aiworker_proto_depIdxs,
		MessageInfos:      file_mediguide_aiworker_v1_aiworker_proto_msgTypes,
	}.Build()
	File_mediguide_aiworker_v1_aiworker_proto = out.File
	file_mediguide_aiworker_v1_aiworker_proto_goTypes = nil
	file_mediguide_aiworker_v1_aiworker_proto_depIdxs = nil
}
