// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: mediguide/aiworker/v1/aiworker.proto

package aiworkerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIWorkerService_AskRAG_FullMethodName          = "/mediguide.aiworker.v1.AIWorkerService/AskRAG"
	AIWorkerService_RunIngestionJob_FullMethodName = "/mediguide.aiworker.v1.AIWorkerService/RunIngestionJob"
)

// AIWorkerServiceClient is the client API for AIWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIWorkerServiceClient interface {
	AskRAG(ctx context.Context, in *AskRAGRequest, opts ...grpc.CallOption) (*AskRAGResponse, error)
	RunIngestionJob(ctx context.Context, in *RunIngestionJobRequest, opts ...grpc.CallOption) (*RunIngestionJobResponse, error)
}

type aIWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIWorkerServiceClient(cc grpc.ClientConnInterface) AIWorkerServiceClient {
	return &aIWorkerServiceClient{cc}
}

func (c *aIWorkerServiceClient) AskRAG(ctx context.Context, in *AskRAGRequest, opts ...grpc.CallOption) (*AskRAGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskRAGResponse)
	err := c.cc.Invoke(ctx, AIWorkerService_AskRAG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIWorkerServiceClient) RunIngestionJob(ctx context.Context, in *RunIngestionJobRequest, opts ...grpc.CallOption) (*RunIngestionJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunIngestionJobResponse)
	err := c.cc.Invoke(ctx, AIWorkerService_RunIngestionJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIWorkerServiceServer is the server API for AIWorkerService service.
// All implementations must embed UnimplementedAIWorkerServiceServer
// for forward compatibility.
type AIWorkerServiceServer interface {
	AskRAG(context.Context, *AskRAGRequest) (*AskRAGResponse, error)
	RunIngestionJob(context.Context, *RunIngestionJobRequest) (*RunIngestionJobResponse, error)
	mustEmbedUnimplementedAIWorkerServiceServer()
}

// UnimplementedAIWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIWorkerServiceServer struct{}

func (UnimplementedAIWorkerServiceServer) AskRAG(context.Context, *AskRAGRequest) (*AskRAGResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AskRAG not implemented")
}
func (UnimplementedAIWorkerServiceServer) RunIngestionJob(context.Context, *RunIngestionJobRequest) (*RunIngestionJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunIngestionJob not implemented")
}
func (UnimplementedAIWorkerServiceServer) mustEmbedUnimplementedAIWorkerServiceServer() {}
func (UnimplementedAIWorkerServiceServer) testEmbeddedByValue()                         {}

// UnsafeAIWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIWorkerServiceServer will
// result in compilation errors.
type UnsafeAIWorkerServiceServer interface {
	mustEmbedUnimplementedAIWorkerServiceServer()
}

func RegisterAIWorkerServiceServer(s grpc.ServiceRegistrar, srv AIWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedAIWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIWorkerService_ServiceDesc, srv)
}

func _AIWorkerService_AskRAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIWorkerServiceServer).AskRAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIWorkerService_AskRAG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIWorkerServiceServer).AskRAG(ctx, req.(*AskRAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIWorkerService_RunIngestionJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunIngestionJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIWorkerServiceServer).RunIngestionJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIWorkerService_RunIngestionJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIWorkerServiceServer).RunIngestionJob(ctx, req.(*RunIngestionJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIWorkerService_ServiceDesc is the grpc.ServiceDesc for AIWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mediguide.aiworker.v1.AIWorkerService",
	HandlerType: (*AIWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskRAG",
			Handler:    _AIWorkerService_AskRAG_Handler,
		},
		{
			MethodName: "RunIngestionJob",
			Handler:    _AIWorkerService_RunIngestionJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mediguide/aiworker/v1/aiworker.proto",
}
