# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mediguide.aiworker.v1 import aiworker_pb2 as mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mediguide/aiworker/v1/aiworker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIWorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskRAG = channel.unary_unary(
                '/mediguide.aiworker.v1.AIWorkerService/AskRAG',
                request_serializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.AskRAGRequest.SerializeToString,
                response_deserializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.AskRAGResponse.FromString,
                _registered_method=True)
        self.RunIngestionJob = channel.unary_unary(
                '/mediguide.aiworker.v1.AIWorkerService/RunIngestionJob',
                request_serializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.RunIngestionJobRequest.SerializeToString,
                response_deserializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.RunIngestionJobResponse.FromString,
                _registered_method=True)


class AIWorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskRAG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunIngestionJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskRAG': grpc.unary_unary_rpc_method_handler(
                    servicer.AskRAG,
                    request_deserializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.AskRAGRequest.FromString,
                    response_serializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.AskRAGResponse.SerializeToString,
            ),
            'RunIngestionJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RunIngestionJob,
                    request_deserializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.RunIngestionJobRequest.FromString,
                    response_serializer=mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.RunIngestionJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mediguide.aiworker.v1.AIWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mediguide.aiworker.v1.AIWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIWorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskRAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mediguide.aiworker.v1.AIWorkerService/AskRAG',
            mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.AskRAGRequest.SerializeToString,
            mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.AskRAGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunIngestionJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mediguide.aiworker.v1.AIWorkerService/RunIngestionJob',
            mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.RunIngestionJobRequest.SerializeToString,
            mediguide_dot_aiworker_dot_v1_dot_aiworker__pb2.RunIngestionJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
